### ISSUE TITLE
Document how to integrate with Rails / Passenger

### ISSUE THREAD

**Issue by dblock** [slack-ruby/slack-ruby-bot#14]
We have https://github.com/dblock/slack-ruby-bot/blob/master/TUTORIAL.md, but could use a clearer example and integration with Rails/Passenger.

**Comment by awh-tokyo** [comment]
Is there anything special that I'm supposed to do to make it work with Passenger?  It works fine in my dev environment but won't stay signed on for more than 5 minutes in Passenger.

**Comment by dblock** [comment]
Do you have any more info, code to share? Where do you run this with Passenger and how is it started?

**Comment by dblock** [comment]
Rails quick walkthrough: http://code.dblock.org/2015/11/28/writing-a-slack-bot-running-on-rails-with-react.html

**Comment by awh-tokyo** [comment]
Basically I did the "Rails quick walkthrough" as you wrote in this commit: https://github.com/dblock/slack-bot-on-rails/commit/a93877ae77d0fa1935b1c847af61dab346a46b78  Really nothing more fancy than that, my bot replies to only one command and I haven't even started on other stuff I need to make it do.  Works beautifully in development (even reconnects after I wake my laptop up from sleep) but in production dies after a few minutes.

I'm using self-hosted Passenger with Apache.  I'm thinking that maybe the non-commercial version doesn't want threads to run continually?  I disabled the "Idle Pool Timeout", but that didn't help.

It's the only application running on the server; at this point I'm so frustrated that I might just throw out Passenger and use some other way to run the app.

**Comment by awh-tokyo** [comment]
Sorry to answer my own question, but I thought I'd put down the solution to help anybody else who's trying to get this working with Passenger.

Basically, by default, the thread will run in the Prefork process, which automatically gets killed if you haven't forked a new process in 5 minutes.  

To keep the prefork process running, set PassengerMaxPreloaderIdleTime to 0.  

You can also arrange for the thread to run in the child process, but you'd probably have to make sure that only one child process runs the thread, even if more than one is forked.  And you'd also have to make sure that child process didn't get killed off (by default they also get killed off after 5 minutes unless it's the only child process).

**Comment by dblock** [comment]
I am not familiar with Passenger, where is all this set? Would you be so kind to contribute a pull request into maybe https://github.com/dblock/slack-ruby-bot/blob/master/DEPLOYMENT.md or another piece of documentation explaining what one has to do with Passenger? Thx.

**Comment by awh-tokyo** [comment]
Will do.  Found (and fixed) another Passenger issue so I'll document that too.

**Comment by dblock** [comment]
:+1:

**Comment by iambanklee** [comment]
@awh-tokyo I had the same issue with Passenger and setting PassengerMaxPreloaderIdleTime to 0 just made it easier - also curious what's the another issue with Passenger?

**Comment by cybercrediators** [comment]
I know this issue is about 2 years old, but since there is no tutorial, maybe some people still want to know wether it's possible to deploy their bot to a self-hosted production environment(?) without rails.

Just change `puma` to `passenger` in your Gemfile and change the `Procfile` accordingly to `web: bundle exec passenger start`. Deploying the bot is now pretty much the walkthrough on the passenger homepage, but you have to add the following (empty) folders to your project `public/`, `tmp/`, `log/`. Furthermore you have to set the `passenger_max_preloader_idle_time 0;` mentioned above, the `passenger_pre_start` option, because otherwise you have to request the page first in order to start the bot process and at least on one deployment I had to set `passenger_startup_file` + type. To maintain the bot, there are logs in your nginx `error.log`, or you can check `passenger-status --verbose` for more information about requests etc. 

``` nginx
server {
  listen 80;
  server_name example.com;
  root /var/www/bot/public;
  passenger_enabled on;
  passenger_max_preloader_idle_time 0;
  passenger_startup_file config.ru;
  passenger_app_type rack;
}

passenger_pre_start http://example.com:80/;
```

All in all, it works pretty good and it's easy to deploy it, but as I said earlier, maybe some people want to know an out of the box instruction for it, because there is still only the heroku tutorial available.

**Comment by dblock** [comment]
Would love it if someone PRed a working example into https://github.com/slack-ruby/slack-ruby-bot/tree/master/examples

**Comment by cybercrediators** [comment]
I'll set up an example with deployment instructions for passenger + apache/nginx

**Comment by boncey** [comment]
I had this problem also for a Sinatra app and [the settings here](https://stackoverflow.com/questions/853532/slow-initial-server-startup-when-using-phusion-passenger-and-rails/853603#853603) fixed it for me.
I added them to my Apache config.

**Comment by dblock** [comment]
@boncey care to contribute some docs?

**Comment by cybercrediators** [comment]
@boncey `PassengerSpawnMethod smart` won't work without `PassengerPreStart`. Tested it with nginx, apache and ruby 2.6.0/2.5.3.

**Comment by dblock** [comment]
Closing via https://github.com/slack-ruby/slack-ruby-bot/pull/214
