### ISSUE TITLE
[question] hooks

### ISSUE THREAD

**Issue by mcritchlow** [slack-ruby/slack-ruby-bot#150]
Hi,

I've successfully got a ping/pong 'hello world' bot setup and integrated into our Slack instance. I'm using `0.10.3`.

I'm trying to get a hook in place to respond to `channel_created` events.

I'm trying to understand the proper way to do this. I'm looking at this options listed here:

https://github.com/slack-ruby/slack-ruby-bot#hooks-registration-on-slackrubybotserver-initialization

I created my app around the [mathbot tutorial](https://github.com/slack-ruby/slack-ruby-bot/blob/master/TUTORIAL.md) example, so I have a bot class, and then I've created a ChannelCreated class following the suggested hierarchy:

```
module SlackLibraryBot
  module Hooks
    class ChannelCreated
      def call(client, data)
      ...
```

I don't however, have a `server` instance as mentioned in the examples, and I'm not clear where that should be instantiated so I can register the class with the server, and what (if anything) the relationship between the Server and the Bot class is. I've tried the following, but the hook doesn't seem to ever get triggered on `channel_created` events

```
     1 require 'slack_library_bot'
     2 require 'web'
     3
     4 Thread.abort_on_exception = true
     5
     6 Thread.new do
     7   begin
     8     SlackLibraryBot::Bot.run
     9     SlackRubyBot::Server.new(hook_handlers: {
    10        channel_created: SlackLibraryBot::Hooks::ChannelCreated.new
    11     })
    12   rescue StandardError => e
    13     STDERR.puts "ERROR: #{e}"
    14     STDERR.puts e.backtrace
    15     raise e
    16   end
    17 end
    18
    19 run SlackLibraryBot::Web
```

Any thoughts or pointers would be most welcome, thanks!

**Comment by mcritchlow** [comment]
i figured out an alternative. not sure it's the best way, but it's working. thanks for the great library btw

**Comment by dblock** [comment]
Can you please post what you did for the next person @mcritchlow? Thanks.

**Comment by mcritchlow** [comment]
@dblock - sure thing. This was one of those 'i have a couple hours on a Friday to try something' kinda days. So I didn't think to do that. As I said, I'm not certain the approach is ideal, and it looks like some changes introduced in the upcoming point release might be a better way forward. In any event, here's what I did, and some feedback/questions.

Gist with relevant bits: https://gist.github.com/mcritchlow/d419acbdeb6f96d3d7a9a1752b49b55c

1. I followed the tutorial as stated above.
2. I added a `server.rb` file alongside the `bot.rb` file
3. Require it in the `slack_library_bot.rb` 
4. I initialize the `server.rb` in `config.ru`

There may be a better way to wire this up. I'd happily take suggestions. FWIW, it did seem like the README for the server section could introduce this context. It at least wasn't immediately obvious to me where the referenced `server` instance would have come from, or best instantiated. Same with the example of bundling the hook into the instantiation of the Server. I'd be happy to submit a PR to clarify either on the tutorial and/or the README, but would want to make sure it's actually the preferred method.

Thanks for the great gem, I'm optimistic we'll be able to use it for our team!

**Comment by dblock** [comment]
Thanks. Please submit any PRs that you think make sense.

**Comment by laertispappas** [comment]
@mcritchlow I don't think your config.ru file is correctly setup on both places ( the example above in the descrption and in the gist file). 

SlackLibraryBot.run is supposed to run a server instance thus it doesn't make any sense to run both .run and creating a new server instance. 

In the descrption appearantly the code is not working because .run is called and run before server initialization. So YourServer.new won't be called since bot.run will run a while loop forever.

Your gist example above is working because you call YourServer.new first and then you run .run class method. This works by accident and the reason behind this is because your custom server is sharing the same hooks datastructure underneath with the libraries super class server ( hooks_support is adding functionality to the included base class). 

@dblock I would suggest to update the documentation with a complete example maybe we should add some wiki pages as well. I would also drop support to create hooks with 3 different ways and as simple and consistent with the api.

Please forgive me if I am mistaken since the above are my observations from my mobile phone reading the code on github but i am pretty sure this is the case.

**Comment by dblock** [comment]
Thanks for debugging this @laertispappas!

**Comment by mcritchlow** [comment]
@laertispappas - Thanks for the feedback, I really appreciate it. I suspect you're right about the gist I posted working by luck of ordering, and your explanation makes good sense.

That said, since I haven't actually had time to dive any deeper into this, so it's not clear to me what the correct/best setup is for a bot that implements server hooks in addition to custom commands (the latter is well documented, imo).

**Comment by mcritchlow** [comment]
Never mind. I think I understand now, had a few more minutes to look at this today. Essentially, the explicit Server instance creation is unnecessary, and as noted, redundant. I could have sworn I tried that before.. But in any event, thanks again to @laertispappas for the clarification on what was going on under the hood. Much appreciated.
