### ISSUE TITLE
Removing github url from "help" output

### ISSUE THREAD

**Issue by Aimpist** [slack-ruby/slack-ruby-bot#221]
Hi ,

I don't want to share Github url in the message which comes if we type "help" to bot

Below is the message which comes
For more information see https://github.com/slack-ruby/slack-ruby-bot, please.

Can we remove this url from the message?

**Comment by dblock** [comment]
You mean [this text](https://github.com/slack-ruby/slack-ruby-bot/blob/master/lib/slack-ruby-bot/commands/help.rb#L35)? You'll have to replace the built in help command with your own.

Does this help? Post how you did it here for the next person.

**Comment by Aimpist** [comment]
That's right.

But I'm not using the repo which you shared. I can see help.rb contains that text.

 The repo which I'm using doesn't have help.rb. Wondering from where then this text is coming?
https://github.com/accessd/slack-deploy-bot    -- This is the one which m using and doesn't contain help.rb.

Also, what is the difference b/w these two repo?
https://github.com/slack-ruby/slack-ruby-bot   - the one which @dblock shared aboved
Vs
https://github.com/accessd/slack-deploy-bot   - the one m using.

**Comment by dblock** [comment]
slack-deploy-bot looks like a bot that uses this library, see https://github.com/accessd/slack-deploy-bot/blob/master/Gemfile#L3. Since it does, the help function comes from here (the link I provided above), and would need to be customized there, in the slack-deploy-bot actual bot.

I'll close this, but feel free to ask more questions here.
