### ISSUE TITLE
Scheduled message

### ISSUE THREAD

**Issue by itmart** [slack-ruby/slack-ruby-bot#227]
Hi,

I've gone through the readme and the tutorial found [here](https://github.com/slack-ruby/slack-ruby-bot/blob/master/TUTORIAL.md) but I still can't figure out how to make my bot send a scheduled message at a specific time every day. Is there a tutorial out there for this? Sorry if this has been asked for or if I'm missing something obvious. Thanks!

**Comment by dblock** [comment]
No such tutorial AFAIK.

I do lots of periodic stuff [like this](https://github.com/dblock/slack-strava/blob/d79c83a969a9b648dc8dec19251bc824dcc76e41/slack-strava/app.rb#L6) and we use https://github.com/socketry/timers. I haven't seen functionality that lets you just do something at a specific time, but you can probably implement something on top of that or contribute to `timers`.

I'll close this since this is not a bot library question, but feel free to ask more questions here.

**Comment by itmart** [comment]
Thank you for your response! I've had experience with the [`whenever gem`](https://github.com/javan/whenever) and I think I can use it but can you take a look at it and see if I can actually use it? I just want to post a message every day, so something like this in the `schedule.rb` file:

```ruby
every 1.day, at: '12:00am' do
  # I'm not sure what to put here, but tell the bot to post a message
end
```

**Comment by dblock** [comment]
Looks reasonable. Inside of that you can try `MyBot.instance.client.call_a_slack_api`.

**Comment by itmart** [comment]
Ah I see. Thank you for your help! I think I have an idea of where to go next and I shall give it a try!
