### ISSUE TITLE
Remove almost-offending giphy attachments

### ISSUE THREAD

**Issue by Startouf** [slack-ruby/slack-ruby-bot#238]
Seriously, although we had a good laugh, this is almost PEGI 18. My team thought I did it on purpose =_=

![Screenshot-2019-10-15-at-18 33 24](https://user-images.githubusercontent.com/7388889/66851164-8224a900-ef7a-11e9-89b1-aafb1093c236.gif)

**Comment by wasabigeek** [comment]
@Startouf the [default rating](https://github.com/slack-ruby/slack-ruby-bot/blob/master/lib/initializers/giphy_client.rb#L18) seems to be set as ["G"](https://developers.giphy.com/docs/optional-settings/#rating), by any chance was the config changed in your app?

As an aside, I can confirm that the image is currently rated "r", although there doesn't seem to be a way to verify if this was changed since the image was uploaded:
![image](https://user-images.githubusercontent.com/4256705/78471240-67c9cc00-7762-11ea-8580-cb85278a174f.png)

**Comment by dblock** [comment]
I decided it's time to remove support for Giphy in #261, especially given the acquisition by Facebook. If anyone cares to do the work, go for it!

**Comment by dblock** [comment]
Support for GIFs was removed in #263.
