### ISSUE TITLE
Add server.on as a shortcut for hooks.add

### ISSUE THREAD

**Issue by dblock** [slack-ruby/slack-ruby-bot#62]
Add `server.on`, eg.

``` ruby
server.hooks.add(:hello, MyBot::Hooks::UserChange.new)
```

could become

``` ruby
server.on :hello do
  # implementation
end
```

cc: @dramalho, thoughts?

**Comment by laertispappas** [comment]
I think that hooks method and the Set  implementation should be deprecated as well since they are implementation details and should not be part of the public API. 

I would like to prepare a PR and add the on shorthand that you proposed. What do you think about the deprecation that I  mentioned above?

Best
LP

**Comment by dblock** [comment]
I'd like to see that code.

**Comment by dblock** [comment]
Resolved via https://github.com/slack-ruby/slack-ruby-bot/pull/147
